GARUDA_RELEASE_STORE_FILE=../../signing/garuda-people-release.keystore
GARUDA_RELEASE_KEY_ALIAS=garuda-people
GARUDA_RELEASE_STORE_PASSWORD=garuda-people-2026
GARUDA_RELEASE_KEY_PASSWORD=garuda-people-2026
